### ISSUE TITLE
[BUG] Big5 workload does not adhere to `max_num_segments`

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-benchmark-workloads#225] opened 2024-03-05 20:49 UTC
### What is the bug?
While specifying `max_num_segments` in the workload parameters to 5 

`opensearch-benchmark execute-test --pipeline=benchmark-only --workload=big5 --target-host="localhost:9200"  --workload-repository="/home/hvamsi/code/opensearch-benchmark-workloads" --kill-running-processes --test-procedure="range" --workload-params="number_of_shards:1,max_num_segments:5"
`

I still see 21 segments 

```
 Heap used for stored fields |                          |           0 |     MB |
|                                                  Segment count |                          |          21 |        |
|                                                 Min Throughput |             index-append |     8037.83 | docs/s |
|                                                Mean Throughput |             index-append |     8642.31 | docs/s |
|                                              Median Throughput |             index-append |     8336.04 | docs/s |
|                                                 Max Throughput |             index-append |     11659.3 | docs/s |
|                                        50th percentile latency |             index-append |     487.442 |     ms |
```

Running operattions:

```
Running delete-index                                                           [100% done]
Running create-index                                                           [100% done]
Running index-append                                                           [100% done]
Running refresh-after-index                                                    [100% done]
Running force-merge                                                            [100% done]
Running refresh-after-force-merge                                              [100% done]
Running wait-until-merges-finish                                               [100% done]
Running range-numeric                                                          [100% done]
```

### How can one reproduce the bug?
Run Big5 workload

### What is the expected behavior?
Number of segments should match workload parameters

**Comment by IanHoang** [comment] 2024-03-12 18:01
Closing this for now as this is not a bug. We can open an enhancement issue for this if desired.

**Closed by IanHoang** 2024-03-12 18:01 UTC
Labels: bug
